CREATE TABLE [dbo].[KeyValueStore](
	[ID] [uniqueidentifier] NOT NULL,
	[StoreName] [nvarchar](450) NOT NULL,
	[Key] [nvarchar](450) NOT NULL,
	[Value] [ntext] NULL,
	[ExpiresAtTicks] [bigint] NULL,
 CONSTRAINT [PK_KeyValueStore] PRIMARY KEY CLUSTERED 
(
	[StoreName] ASC,
	[Key] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [IX_KeyValueStore_ExpiresAtTicks] ON [dbo].[KeyValueStore]
(
	[ExpiresAtTicks] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [IX_KeyValueStore_ID] ON [dbo].[KeyValueStore]
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



CREATE NONCLUSTERED INDEX [IX_KeyValueStore_Key] ON [dbo].[KeyValueStore]
(
	[Key] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



CREATE NONCLUSTERED INDEX [IX_KeyValueStore_StoreName] ON [dbo].[KeyValueStore]
(
	[StoreName] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO