IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'WebHookRequest'))
BEGIN

	CREATE TABLE [dbo].[WebHookRequest](

		[ID] [uniqueidentifier] NOT NULL,
		[HandlingHost] [nvarchar](450) NULL,
		[Source] [nvarchar](450) NULL,
		[HappenedAt] [datetime2](7) NOT NULL,
		[MetaJson] [ntext] NULL,
		[PayloadJson] [ntext] NULL,

	CONSTRAINT [PK_WebHookRequest] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [IX_WebHookRequest_HandlingHost] ON [dbo].[WebHookRequest]
	(
		[HandlingHost] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [IX_WebHookRequest_Source] ON [dbo].[WebHookRequest]
	(
		[Source] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [IX_WebHookRequest_HappenedAt] ON [dbo].[WebHookRequest]
	(
		[HappenedAt] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

END